export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_ITEM_QUANTITY = "CHANGE_ITEM_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const ADD_USER_ADDRESS = "ADD_USER_ADDRESS";
export const REMOVE_USER_ADDRESS = "REMOVE_USER_ADDRESS";
export const ADD_ORDER_ITEMS = "ADD_ORDER_ITEMS";
export const REMOVE_ORDER_ITEMS = "REMOVE_ORDER_ITEMS";

